### PR TITLE
Add bool type

### PR DESCRIPTION
**Pull request by frack113**
HI,
Last week I had to fix rule with a bool value in yaml because many backend in sigmac don't manage it.
So I think to add a type SigmaBool.
Next is to think how deal with.
- It should be only a equal (no contains, start....).
- Backend that don't support convert SigmaBool to SigmaString

### CODE REVIEW

**Comment by thomaspatzke** [comment]
Added some tests.

**Comment by thomaspatzke** [comment]
Thanks for discovering this! I'm implementing the handling of booleans in the base backends, which will forbid them as standalone values and appearance in other contexts except the simple equal operator. Regarding backend handling of text-based backends I implement additional template variables for the two values which also implies that these can be quoted strings.

**Comment by thomaspatzke** [comment]
Base backend code is now implemented, too. Also used this opportunity to disallow standalone CIDR values, as I don't see any use-case for unbound CIDR values and the code is quite complex.

**Comment by frack113** [comment]
Thanks for the implementation.
With hindsight the 'unbound CIDR' doesn't make sense

**Pull request merged**
