### PR TITLE
Python 3.8 EOL

### PR DESCRIPTION
**Pull request by frack113**
https://devguide.python.org/versions/

As 3.8 is finally at the end of life, I remove it

Did NOT edit the release.yml : 
- actions/setup-python@v4 -> v5
- python-version: 3.8 -> 3.9 ?

Test faild with Python 3.13, I haven't dug yet

### CODE REVIEW

**Comment by thomaspatzke** [comment]
Still struggling on this:

* Pro: no dependency on EOL Pythons.
* Pro: new features can be used. There were several occasions where I wrote less nice code just for the 3.8 compatibility. These could now be rewritten. Sticking on old Pythons would block progress.
* Against: Lots of stuff depends on EOL Pythons, e.g. Ubuntu LTS like 20.04 (but newer installable), Splunk (lost anyways, they use 3.7!).

I tend to *Pro* and merge. What do you think?

**Comment by branchvincent** [comment]
fyi #289 presumably fixes the 3.13 test failures

**Comment by thomaspatzke** [comment]
Ok, let's do it this way!

**Review by thomaspatzke — CHANGES_REQUESTED** [review]
Can you also change the deployment/publish flow to a newer one?

**Comment by frack113** [comment]
Can be Squash and merge, too many commit to make a simple change 😄

**Review by thomaspatzke — APPROVED** [review]

**Pull request merged**
