### PR TITLE
Add more  validators

### PR DESCRIPTION
**Pull request by frack113**
Fix:
- DateExistenceValidator

Add:
- CustomAttributesValidator
- DescriptionExistenceValidator
- DescriptionLengthValidator
- LevelExistenceValidator
- NamespaceTagValidator

Chore:
- Update Readme
- change `== None` to `is None` 
- split test_validator.py to facilitate updating
- small typo fix

### CODE REVIEW

**Comment by Res260** [comment]
Sorry for commenting on an merged PR, but doesn't the `NamespaceTagValidator` go against the sigma specification? Tag namespaces are not enforced in the spec, it says to use them "if applicable". I guess we can always exclude the validator if needed, but I feel like the default pysigma validators should not restrict the sigma spec
@frack113 @thomaspatzke

**Comment by thomaspatzke** [comment]
The validators are optional checks for rule best-practices and enforced as additional quality criterion in the SigmaHQ rule repo.

**Comment by thomaspatzke** [comment]
Another examples are the wildcard instead of startswith, endswith or contains validators. It's not specified but we enforce them in the repo to maintain a consistent rule style.

**Comment by Res260** [comment]
Shouldn't the sigmaHQ/sigma specific validators then be specified in the sigmaH/sigma repo?

The reason i'm asking is because I was under the impression the pySigma library had no link to the sigmaHQ/sigma repo and was meant for repo-agnostic usage. We internally use these builtin validators. I'll do some exclusions in that case :)

**Comment by thomaspatzke** [comment]
This would basically mean maintaining the majority of validators in a separate repository that must be kept in sync with pySigma etc. Lots of effort for the sake of separation, so we put them together in the pySigma project 😉

**Comment by thomaspatzke** [comment]
BTW, there are mutually exclusive validators like for different versions of the TLP protocol, so you should use them with care anyways 😉

**Comment by frack113** [comment]
I use "sigmahq" when it isn't too generic :
https://github.com/SigmaHQ/pySigma/blob/80902f2db11bdd57f2ee7d48c483c24d5cdbcd90/sigma/validators/core/metadata.py#L209

You can use a config file like this one : 
https://github.com/SigmaHQ/sigma/blob/2d63859aed1fd62630c3b30b3e51786647699dbf/tests/sigma_cli_conf.yml

You can remove some from all 😉

```yaml
validators:
    - all
    - -tlptag
    - -tlpv1_tag
 ```

**Pull request merged**
